/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as ContatoRouteImport } from './routes/contato'
import { Route as DeliveryRouteImport } from './routes/delivery'
import { Route as EquipeRouteImport } from './routes/equipe'
import { Route as EventosRouteImport } from './routes/eventos'
import { Route as LoginRouteImport } from './routes/login'
import { Route as LojaRouteImport } from './routes/loja'
import { Route as MinhaContaRouteImport } from './routes/minha-conta'
import { Route as ServicosRouteImport } from './routes/servicos'
import { Route as SobreRouteImport } from './routes/sobre'
import { Route as BCodigoRouteImport } from './routes/b.$codigo'
import { Route as LojaIdRouteImport } from './routes/loja_.$id'
import { Route as OsNumeroRouteImport } from './routes/os.$numero'
import { Route as LojaProdutoIdRouteImport } from './routes/loja_.produto.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const ContatoRoute = ContatoRouteImport.update({
  id: '/contato',
  path: '/contato',
  getParentRoute: () => rootRouteImport,
} as any)
const DeliveryRoute = DeliveryRouteImport.update({
  id: '/delivery',
  path: '/delivery',
  getParentRoute: () => rootRouteImport,
} as any)
const EquipeRoute = EquipeRouteImport.update({
  id: '/equipe',
  path: '/equipe',
  getParentRoute: () => rootRouteImport,
} as any)
const EventosRoute = EventosRouteImport.update({
  id: '/eventos',
  path: '/eventos',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LojaRoute = LojaRouteImport.update({
  id: '/loja',
  path: '/loja',
  getParentRoute: () => rootRouteImport,
} as any)
const MinhaContaRoute = MinhaContaRouteImport.update({
  id: '/minha-conta',
  path: '/minha-conta',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicosRoute = ServicosRouteImport.update({
  id: '/servicos',
  path: '/servicos',
  getParentRoute: () => rootRouteImport,
} as any)
const SobreRoute = SobreRouteImport.update({
  id: '/sobre',
  path: '/sobre',
  getParentRoute: () => rootRouteImport,
} as any)
const BCodigoRoute = BCodigoRouteImport.update({
  id: '/b/$codigo',
  path: '/b/$codigo',
  getParentRoute: () => rootRouteImport,
} as any)
const LojaIdRoute = LojaIdRouteImport.update({
  id: '/loja_/$id',
  path: '/loja/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const OsNumeroRoute = OsNumeroRouteImport.update({
  id: '/os/$numero',
  path: '/os/$numero',
  getParentRoute: () => rootRouteImport,
} as any)
const LojaProdutoIdRoute = LojaProdutoIdRouteImport.update({
  id: '/loja_/produto/$id',
  path: '/loja/produto/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/contato': typeof ContatoRoute
  '/delivery': typeof DeliveryRoute
  '/equipe': typeof EquipeRoute
  '/eventos': typeof EventosRoute
  '/login': typeof LoginRoute
  '/loja': typeof LojaRoute
  '/minha-conta': typeof MinhaContaRoute
  '/servicos': typeof ServicosRoute
  '/sobre': typeof SobreRoute
  '/b/$codigo': typeof BCodigoRoute
  '/loja/$id': typeof LojaIdRoute
  '/os/$numero': typeof OsNumeroRoute
  '/loja/produto/$id': typeof LojaProdutoIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/contato': typeof ContatoRoute
  '/delivery': typeof DeliveryRoute
  '/equipe': typeof EquipeRoute
  '/eventos': typeof EventosRoute
  '/login': typeof LoginRoute
  '/loja': typeof LojaRoute
  '/minha-conta': typeof MinhaContaRoute
  '/servicos': typeof ServicosRoute
  '/sobre': typeof SobreRoute
  '/b/$codigo': typeof BCodigoRoute
  '/loja/$id': typeof LojaIdRoute
  '/os/$numero': typeof OsNumeroRoute
  '/loja/produto/$id': typeof LojaProdutoIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/contato': typeof ContatoRoute
  '/delivery': typeof DeliveryRoute
  '/equipe': typeof EquipeRoute
  '/eventos': typeof EventosRoute
  '/login': typeof LoginRoute
  '/loja': typeof LojaRoute
  '/minha-conta': typeof MinhaContaRoute
  '/servicos': typeof ServicosRoute
  '/sobre': typeof SobreRoute
  '/b/$codigo': typeof BCodigoRoute
  '/loja_/$id': typeof LojaIdRoute
  '/os/$numero': typeof OsNumeroRoute
  '/loja_/produto/$id': typeof LojaProdutoIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/contato'
    | '/delivery'
    | '/equipe'
    | '/eventos'
    | '/login'
    | '/loja'
    | '/minha-conta'
    | '/servicos'
    | '/sobre'
    | '/b/$codigo'
    | '/loja/$id'
    | '/os/$numero'
    | '/loja/produto/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/contato'
    | '/delivery'
    | '/equipe'
    | '/eventos'
    | '/login'
    | '/loja'
    | '/minha-conta'
    | '/servicos'
    | '/sobre'
    | '/b/$codigo'
    | '/loja/$id'
    | '/os/$numero'
    | '/loja/produto/$id'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/contato'
    | '/delivery'
    | '/equipe'
    | '/eventos'
    | '/login'
    | '/loja'
    | '/minha-conta'
    | '/servicos'
    | '/sobre'
    | '/b/$codigo'
    | '/loja_/$id'
    | '/os/$numero'
    | '/loja_/produto/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  ContatoRoute: typeof ContatoRoute
  DeliveryRoute: typeof DeliveryRoute
  EquipeRoute: typeof EquipeRoute
  EventosRoute: typeof EventosRoute
  LoginRoute: typeof LoginRoute
  LojaRoute: typeof LojaRoute
  MinhaContaRoute: typeof MinhaContaRoute
  ServicosRoute: typeof ServicosRoute
  SobreRoute: typeof SobreRoute
  BCodigoRoute: typeof BCodigoRoute
  LojaIdRoute: typeof LojaIdRoute
  OsNumeroRoute: typeof OsNumeroRoute
  LojaProdutoIdRoute: typeof LojaProdutoIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contato': {
      id: '/contato'
      path: '/contato'
      fullPath: '/contato'
      preLoaderRoute: typeof ContatoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/delivery': {
      id: '/delivery'
      path: '/delivery'
      fullPath: '/delivery'
      preLoaderRoute: typeof DeliveryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/equipe': {
      id: '/equipe'
      path: '/equipe'
      fullPath: '/equipe'
      preLoaderRoute: typeof EquipeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/eventos': {
      id: '/eventos'
      path: '/eventos'
      fullPath: '/eventos'
      preLoaderRoute: typeof EventosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/loja': {
      id: '/loja'
      path: '/loja'
      fullPath: '/loja'
      preLoaderRoute: typeof LojaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/minha-conta': {
      id: '/minha-conta'
      path: '/minha-conta'
      fullPath: '/minha-conta'
      preLoaderRoute: typeof MinhaContaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/servicos': {
      id: '/servicos'
      path: '/servicos'
      fullPath: '/servicos'
      preLoaderRoute: typeof ServicosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sobre': {
      id: '/sobre'
      path: '/sobre'
      fullPath: '/sobre'
      preLoaderRoute: typeof SobreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/b/$codigo': {
      id: '/b/$codigo'
      path: '/b/$codigo'
      fullPath: '/b/$codigo'
      preLoaderRoute: typeof BCodigoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/loja_/$id': {
      id: '/loja_/$id'
      path: '/loja/$id'
      fullPath: '/loja/$id'
      preLoaderRoute: typeof LojaIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/os/$numero': {
      id: '/os/$numero'
      path: '/os/$numero'
      fullPath: '/os/$numero'
      preLoaderRoute: typeof OsNumeroRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/loja_/produto/$id': {
      id: '/loja_/produto/$id'
      path: '/loja/produto/$id'
      fullPath: '/loja/produto/$id'
      preLoaderRoute: typeof LojaProdutoIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  ContatoRoute: ContatoRoute,
  DeliveryRoute: DeliveryRoute,
  EquipeRoute: EquipeRoute,
  EventosRoute: EventosRoute,
  LoginRoute: LoginRoute,
  LojaRoute: LojaRoute,
  MinhaContaRoute: MinhaContaRoute,
  ServicosRoute: ServicosRoute,
  SobreRoute: SobreRoute,
  BCodigoRoute: BCodigoRoute,
  LojaIdRoute: LojaIdRoute,
  OsNumeroRoute: OsNumeroRoute,
  LojaProdutoIdRoute: LojaProdutoIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
