/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SobreRouteImport } from './routes/sobre'
import { Route as ServicosRouteImport } from './routes/servicos'
import { Route as LojaRouteImport } from './routes/loja'
import { Route as EventosRouteImport } from './routes/eventos'
import { Route as EquipeRouteImport } from './routes/equipe'
import { Route as DeliveryRouteImport } from './routes/delivery'
import { Route as ContatoRouteImport } from './routes/contato'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LojaIdRouteImport } from './routes/loja_.$id'
import { Route as LojaProdutoIdRouteImport } from './routes/loja_.produto.$id'

const SobreRoute = SobreRouteImport.update({
  id: '/sobre',
  path: '/sobre',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicosRoute = ServicosRouteImport.update({
  id: '/servicos',
  path: '/servicos',
  getParentRoute: () => rootRouteImport,
} as any)
const LojaRoute = LojaRouteImport.update({
  id: '/loja',
  path: '/loja',
  getParentRoute: () => rootRouteImport,
} as any)
const EventosRoute = EventosRouteImport.update({
  id: '/eventos',
  path: '/eventos',
  getParentRoute: () => rootRouteImport,
} as any)
const EquipeRoute = EquipeRouteImport.update({
  id: '/equipe',
  path: '/equipe',
  getParentRoute: () => rootRouteImport,
} as any)
const DeliveryRoute = DeliveryRouteImport.update({
  id: '/delivery',
  path: '/delivery',
  getParentRoute: () => rootRouteImport,
} as any)
const ContatoRoute = ContatoRouteImport.update({
  id: '/contato',
  path: '/contato',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LojaIdRoute = LojaIdRouteImport.update({
  id: '/loja_/$id',
  path: '/loja/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const LojaProdutoIdRoute = LojaProdutoIdRouteImport.update({
  id: '/loja_/produto/$id',
  path: '/loja/produto/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/contato': typeof ContatoRoute
  '/delivery': typeof DeliveryRoute
  '/equipe': typeof EquipeRoute
  '/eventos': typeof EventosRoute
  '/loja': typeof LojaRoute
  '/servicos': typeof ServicosRoute
  '/sobre': typeof SobreRoute
  '/loja/$id': typeof LojaIdRoute
  '/loja/produto/$id': typeof LojaProdutoIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/contato': typeof ContatoRoute
  '/delivery': typeof DeliveryRoute
  '/equipe': typeof EquipeRoute
  '/eventos': typeof EventosRoute
  '/loja': typeof LojaRoute
  '/servicos': typeof ServicosRoute
  '/sobre': typeof SobreRoute
  '/loja/$id': typeof LojaIdRoute
  '/loja/produto/$id': typeof LojaProdutoIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/contato': typeof ContatoRoute
  '/delivery': typeof DeliveryRoute
  '/equipe': typeof EquipeRoute
  '/eventos': typeof EventosRoute
  '/loja': typeof LojaRoute
  '/servicos': typeof ServicosRoute
  '/sobre': typeof SobreRoute
  '/loja_/$id': typeof LojaIdRoute
  '/loja_/produto/$id': typeof LojaProdutoIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/contato'
    | '/delivery'
    | '/equipe'
    | '/eventos'
    | '/loja'
    | '/servicos'
    | '/sobre'
    | '/loja/$id'
    | '/loja/produto/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/contato'
    | '/delivery'
    | '/equipe'
    | '/eventos'
    | '/loja'
    | '/servicos'
    | '/sobre'
    | '/loja/$id'
    | '/loja/produto/$id'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/contato'
    | '/delivery'
    | '/equipe'
    | '/eventos'
    | '/loja'
    | '/servicos'
    | '/sobre'
    | '/loja_/$id'
    | '/loja_/produto/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  ContatoRoute: typeof ContatoRoute
  DeliveryRoute: typeof DeliveryRoute
  EquipeRoute: typeof EquipeRoute
  EventosRoute: typeof EventosRoute
  LojaRoute: typeof LojaRoute
  ServicosRoute: typeof ServicosRoute
  SobreRoute: typeof SobreRoute
  LojaIdRoute: typeof LojaIdRoute
  LojaProdutoIdRoute: typeof LojaProdutoIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sobre': {
      id: '/sobre'
      path: '/sobre'
      fullPath: '/sobre'
      preLoaderRoute: typeof SobreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/servicos': {
      id: '/servicos'
      path: '/servicos'
      fullPath: '/servicos'
      preLoaderRoute: typeof ServicosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/loja': {
      id: '/loja'
      path: '/loja'
      fullPath: '/loja'
      preLoaderRoute: typeof LojaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/eventos': {
      id: '/eventos'
      path: '/eventos'
      fullPath: '/eventos'
      preLoaderRoute: typeof EventosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/equipe': {
      id: '/equipe'
      path: '/equipe'
      fullPath: '/equipe'
      preLoaderRoute: typeof EquipeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/delivery': {
      id: '/delivery'
      path: '/delivery'
      fullPath: '/delivery'
      preLoaderRoute: typeof DeliveryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contato': {
      id: '/contato'
      path: '/contato'
      fullPath: '/contato'
      preLoaderRoute: typeof ContatoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/loja_/$id': {
      id: '/loja_/$id'
      path: '/loja/$id'
      fullPath: '/loja/$id'
      preLoaderRoute: typeof LojaIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/loja_/produto/$id': {
      id: '/loja_/produto/$id'
      path: '/loja/produto/$id'
      fullPath: '/loja/produto/$id'
      preLoaderRoute: typeof LojaProdutoIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  ContatoRoute: ContatoRoute,
  DeliveryRoute: DeliveryRoute,
  EquipeRoute: EquipeRoute,
  EventosRoute: EventosRoute,
  LojaRoute: LojaRoute,
  ServicosRoute: ServicosRoute,
  SobreRoute: SobreRoute,
  LojaIdRoute: LojaIdRoute,
  LojaProdutoIdRoute: LojaProdutoIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
