/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppRouteImport } from './routes/_app'
import { Route as AppIndexRouteImport } from './routes/_app.index'
import { Route as AppVendasRouteImport } from './routes/_app.vendas'
import { Route as AppTiposAtividadeRouteImport } from './routes/_app.tipos-atividade'
import { Route as AppRelatoriosRouteImport } from './routes/_app.relatorios'
import { Route as AppPrecosRouteImport } from './routes/_app.precos'
import { Route as AppPendenciasRouteImport } from './routes/_app.pendencias'
import { Route as AppParametrosNfeRouteImport } from './routes/_app.parametros-nfe'
import { Route as AppParametrosFinanceirosRouteImport } from './routes/_app.parametros-financeiros'
import { Route as AppOficinaRouteImport } from './routes/_app.oficina'
import { Route as AppMarketingRouteImport } from './routes/_app.marketing'
import { Route as AppMarcasRouteImport } from './routes/_app.marcas'
import { Route as AppFornecedoresRouteImport } from './routes/_app.fornecedores'
import { Route as AppFechamentoRouteImport } from './routes/_app.fechamento'
import { Route as AppDespesasRouteImport } from './routes/_app.despesas'
import { Route as AppContasAPagarRouteImport } from './routes/_app.contas-a-pagar'
import { Route as AppConfiguracoesRouteImport } from './routes/_app.configuracoes'
import { Route as AppComprasRouteImport } from './routes/_app.compras'
import { Route as AppClientesRouteImport } from './routes/_app.clientes'
import { Route as AppBikesRouteImport } from './routes/_app.bikes'
import { Route as AppVendasIndexRouteImport } from './routes/_app.vendas.index'
import { Route as AppVendasIdRouteImport } from './routes/_app.vendas_.$id'
import { Route as AppVendasProdutosRouteImport } from './routes/_app.vendas.produtos'
import { Route as AppVendasNovaRouteImport } from './routes/_app.vendas.nova'
import { Route as AppVendasLojaVirtualRouteImport } from './routes/_app.vendas.loja-virtual'
import { Route as AppVendasEstoqueRouteImport } from './routes/_app.vendas.estoque'
import { Route as AppOficinaOrdensRouteImport } from './routes/_app.oficina_.ordens'
import { Route as AppOficinaNovaRouteImport } from './routes/_app.oficina_.nova'
import { Route as AppFornecedoresIdRouteImport } from './routes/_app.fornecedores_.$id'
import { Route as AppClientesNovaRouteImport } from './routes/_app.clientes_.nova'
import { Route as AppClientesIdRouteImport } from './routes/_app.clientes_.$id'
import { Route as AppBikesIdRouteImport } from './routes/_app.bikes_.$id'
import { Route as AppBCodigoRouteImport } from './routes/_app.b.$codigo'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppVendasRoute = AppVendasRouteImport.update({
  id: '/vendas',
  path: '/vendas',
  getParentRoute: () => AppRoute,
} as any)
const AppTiposAtividadeRoute = AppTiposAtividadeRouteImport.update({
  id: '/tipos-atividade',
  path: '/tipos-atividade',
  getParentRoute: () => AppRoute,
} as any)
const AppRelatoriosRoute = AppRelatoriosRouteImport.update({
  id: '/relatorios',
  path: '/relatorios',
  getParentRoute: () => AppRoute,
} as any)
const AppPrecosRoute = AppPrecosRouteImport.update({
  id: '/precos',
  path: '/precos',
  getParentRoute: () => AppRoute,
} as any)
const AppPendenciasRoute = AppPendenciasRouteImport.update({
  id: '/pendencias',
  path: '/pendencias',
  getParentRoute: () => AppRoute,
} as any)
const AppParametrosNfeRoute = AppParametrosNfeRouteImport.update({
  id: '/parametros-nfe',
  path: '/parametros-nfe',
  getParentRoute: () => AppRoute,
} as any)
const AppParametrosFinanceirosRoute =
  AppParametrosFinanceirosRouteImport.update({
    id: '/parametros-financeiros',
    path: '/parametros-financeiros',
    getParentRoute: () => AppRoute,
  } as any)
const AppOficinaRoute = AppOficinaRouteImport.update({
  id: '/oficina',
  path: '/oficina',
  getParentRoute: () => AppRoute,
} as any)
const AppMarketingRoute = AppMarketingRouteImport.update({
  id: '/marketing',
  path: '/marketing',
  getParentRoute: () => AppRoute,
} as any)
const AppMarcasRoute = AppMarcasRouteImport.update({
  id: '/marcas',
  path: '/marcas',
  getParentRoute: () => AppRoute,
} as any)
const AppFornecedoresRoute = AppFornecedoresRouteImport.update({
  id: '/fornecedores',
  path: '/fornecedores',
  getParentRoute: () => AppRoute,
} as any)
const AppFechamentoRoute = AppFechamentoRouteImport.update({
  id: '/fechamento',
  path: '/fechamento',
  getParentRoute: () => AppRoute,
} as any)
const AppDespesasRoute = AppDespesasRouteImport.update({
  id: '/despesas',
  path: '/despesas',
  getParentRoute: () => AppRoute,
} as any)
const AppContasAPagarRoute = AppContasAPagarRouteImport.update({
  id: '/contas-a-pagar',
  path: '/contas-a-pagar',
  getParentRoute: () => AppRoute,
} as any)
const AppConfiguracoesRoute = AppConfiguracoesRouteImport.update({
  id: '/configuracoes',
  path: '/configuracoes',
  getParentRoute: () => AppRoute,
} as any)
const AppComprasRoute = AppComprasRouteImport.update({
  id: '/compras',
  path: '/compras',
  getParentRoute: () => AppRoute,
} as any)
const AppClientesRoute = AppClientesRouteImport.update({
  id: '/clientes',
  path: '/clientes',
  getParentRoute: () => AppRoute,
} as any)
const AppBikesRoute = AppBikesRouteImport.update({
  id: '/bikes',
  path: '/bikes',
  getParentRoute: () => AppRoute,
} as any)
const AppVendasIndexRoute = AppVendasIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppVendasRoute,
} as any)
const AppVendasIdRoute = AppVendasIdRouteImport.update({
  id: '/vendas_/$id',
  path: '/vendas/$id',
  getParentRoute: () => AppRoute,
} as any)
const AppVendasProdutosRoute = AppVendasProdutosRouteImport.update({
  id: '/produtos',
  path: '/produtos',
  getParentRoute: () => AppVendasRoute,
} as any)
const AppVendasNovaRoute = AppVendasNovaRouteImport.update({
  id: '/nova',
  path: '/nova',
  getParentRoute: () => AppVendasRoute,
} as any)
const AppVendasLojaVirtualRoute = AppVendasLojaVirtualRouteImport.update({
  id: '/loja-virtual',
  path: '/loja-virtual',
  getParentRoute: () => AppVendasRoute,
} as any)
const AppVendasEstoqueRoute = AppVendasEstoqueRouteImport.update({
  id: '/estoque',
  path: '/estoque',
  getParentRoute: () => AppVendasRoute,
} as any)
const AppOficinaOrdensRoute = AppOficinaOrdensRouteImport.update({
  id: '/oficina_/ordens',
  path: '/oficina/ordens',
  getParentRoute: () => AppRoute,
} as any)
const AppOficinaNovaRoute = AppOficinaNovaRouteImport.update({
  id: '/oficina_/nova',
  path: '/oficina/nova',
  getParentRoute: () => AppRoute,
} as any)
const AppFornecedoresIdRoute = AppFornecedoresIdRouteImport.update({
  id: '/fornecedores_/$id',
  path: '/fornecedores/$id',
  getParentRoute: () => AppRoute,
} as any)
const AppClientesNovaRoute = AppClientesNovaRouteImport.update({
  id: '/clientes_/nova',
  path: '/clientes/nova',
  getParentRoute: () => AppRoute,
} as any)
const AppClientesIdRoute = AppClientesIdRouteImport.update({
  id: '/clientes_/$id',
  path: '/clientes/$id',
  getParentRoute: () => AppRoute,
} as any)
const AppBikesIdRoute = AppBikesIdRouteImport.update({
  id: '/bikes_/$id',
  path: '/bikes/$id',
  getParentRoute: () => AppRoute,
} as any)
const AppBCodigoRoute = AppBCodigoRouteImport.update({
  id: '/b/$codigo',
  path: '/b/$codigo',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/login': typeof LoginRoute
  '/bikes': typeof AppBikesRoute
  '/clientes': typeof AppClientesRoute
  '/compras': typeof AppComprasRoute
  '/configuracoes': typeof AppConfiguracoesRoute
  '/contas-a-pagar': typeof AppContasAPagarRoute
  '/despesas': typeof AppDespesasRoute
  '/fechamento': typeof AppFechamentoRoute
  '/fornecedores': typeof AppFornecedoresRoute
  '/marcas': typeof AppMarcasRoute
  '/marketing': typeof AppMarketingRoute
  '/oficina': typeof AppOficinaRoute
  '/parametros-financeiros': typeof AppParametrosFinanceirosRoute
  '/parametros-nfe': typeof AppParametrosNfeRoute
  '/pendencias': typeof AppPendenciasRoute
  '/precos': typeof AppPrecosRoute
  '/relatorios': typeof AppRelatoriosRoute
  '/tipos-atividade': typeof AppTiposAtividadeRoute
  '/vendas': typeof AppVendasRouteWithChildren
  '/b/$codigo': typeof AppBCodigoRoute
  '/bikes/$id': typeof AppBikesIdRoute
  '/clientes/$id': typeof AppClientesIdRoute
  '/clientes/nova': typeof AppClientesNovaRoute
  '/fornecedores/$id': typeof AppFornecedoresIdRoute
  '/oficina/nova': typeof AppOficinaNovaRoute
  '/oficina/ordens': typeof AppOficinaOrdensRoute
  '/vendas/estoque': typeof AppVendasEstoqueRoute
  '/vendas/loja-virtual': typeof AppVendasLojaVirtualRoute
  '/vendas/nova': typeof AppVendasNovaRoute
  '/vendas/produtos': typeof AppVendasProdutosRoute
  '/vendas/$id': typeof AppVendasIdRoute
  '/vendas/': typeof AppVendasIndexRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/bikes': typeof AppBikesRoute
  '/clientes': typeof AppClientesRoute
  '/compras': typeof AppComprasRoute
  '/configuracoes': typeof AppConfiguracoesRoute
  '/contas-a-pagar': typeof AppContasAPagarRoute
  '/despesas': typeof AppDespesasRoute
  '/fechamento': typeof AppFechamentoRoute
  '/fornecedores': typeof AppFornecedoresRoute
  '/marcas': typeof AppMarcasRoute
  '/marketing': typeof AppMarketingRoute
  '/oficina': typeof AppOficinaRoute
  '/parametros-financeiros': typeof AppParametrosFinanceirosRoute
  '/parametros-nfe': typeof AppParametrosNfeRoute
  '/pendencias': typeof AppPendenciasRoute
  '/precos': typeof AppPrecosRoute
  '/relatorios': typeof AppRelatoriosRoute
  '/tipos-atividade': typeof AppTiposAtividadeRoute
  '/': typeof AppIndexRoute
  '/b/$codigo': typeof AppBCodigoRoute
  '/bikes/$id': typeof AppBikesIdRoute
  '/clientes/$id': typeof AppClientesIdRoute
  '/clientes/nova': typeof AppClientesNovaRoute
  '/fornecedores/$id': typeof AppFornecedoresIdRoute
  '/oficina/nova': typeof AppOficinaNovaRoute
  '/oficina/ordens': typeof AppOficinaOrdensRoute
  '/vendas/estoque': typeof AppVendasEstoqueRoute
  '/vendas/loja-virtual': typeof AppVendasLojaVirtualRoute
  '/vendas/nova': typeof AppVendasNovaRoute
  '/vendas/produtos': typeof AppVendasProdutosRoute
  '/vendas/$id': typeof AppVendasIdRoute
  '/vendas': typeof AppVendasIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/_app/bikes': typeof AppBikesRoute
  '/_app/clientes': typeof AppClientesRoute
  '/_app/compras': typeof AppComprasRoute
  '/_app/configuracoes': typeof AppConfiguracoesRoute
  '/_app/contas-a-pagar': typeof AppContasAPagarRoute
  '/_app/despesas': typeof AppDespesasRoute
  '/_app/fechamento': typeof AppFechamentoRoute
  '/_app/fornecedores': typeof AppFornecedoresRoute
  '/_app/marcas': typeof AppMarcasRoute
  '/_app/marketing': typeof AppMarketingRoute
  '/_app/oficina': typeof AppOficinaRoute
  '/_app/parametros-financeiros': typeof AppParametrosFinanceirosRoute
  '/_app/parametros-nfe': typeof AppParametrosNfeRoute
  '/_app/pendencias': typeof AppPendenciasRoute
  '/_app/precos': typeof AppPrecosRoute
  '/_app/relatorios': typeof AppRelatoriosRoute
  '/_app/tipos-atividade': typeof AppTiposAtividadeRoute
  '/_app/vendas': typeof AppVendasRouteWithChildren
  '/_app/': typeof AppIndexRoute
  '/_app/b/$codigo': typeof AppBCodigoRoute
  '/_app/bikes_/$id': typeof AppBikesIdRoute
  '/_app/clientes_/$id': typeof AppClientesIdRoute
  '/_app/clientes_/nova': typeof AppClientesNovaRoute
  '/_app/fornecedores_/$id': typeof AppFornecedoresIdRoute
  '/_app/oficina_/nova': typeof AppOficinaNovaRoute
  '/_app/oficina_/ordens': typeof AppOficinaOrdensRoute
  '/_app/vendas/estoque': typeof AppVendasEstoqueRoute
  '/_app/vendas/loja-virtual': typeof AppVendasLojaVirtualRoute
  '/_app/vendas/nova': typeof AppVendasNovaRoute
  '/_app/vendas/produtos': typeof AppVendasProdutosRoute
  '/_app/vendas_/$id': typeof AppVendasIdRoute
  '/_app/vendas/': typeof AppVendasIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/bikes'
    | '/clientes'
    | '/compras'
    | '/configuracoes'
    | '/contas-a-pagar'
    | '/despesas'
    | '/fechamento'
    | '/fornecedores'
    | '/marcas'
    | '/marketing'
    | '/oficina'
    | '/parametros-financeiros'
    | '/parametros-nfe'
    | '/pendencias'
    | '/precos'
    | '/relatorios'
    | '/tipos-atividade'
    | '/vendas'
    | '/b/$codigo'
    | '/bikes/$id'
    | '/clientes/$id'
    | '/clientes/nova'
    | '/fornecedores/$id'
    | '/oficina/nova'
    | '/oficina/ordens'
    | '/vendas/estoque'
    | '/vendas/loja-virtual'
    | '/vendas/nova'
    | '/vendas/produtos'
    | '/vendas/$id'
    | '/vendas/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/bikes'
    | '/clientes'
    | '/compras'
    | '/configuracoes'
    | '/contas-a-pagar'
    | '/despesas'
    | '/fechamento'
    | '/fornecedores'
    | '/marcas'
    | '/marketing'
    | '/oficina'
    | '/parametros-financeiros'
    | '/parametros-nfe'
    | '/pendencias'
    | '/precos'
    | '/relatorios'
    | '/tipos-atividade'
    | '/'
    | '/b/$codigo'
    | '/bikes/$id'
    | '/clientes/$id'
    | '/clientes/nova'
    | '/fornecedores/$id'
    | '/oficina/nova'
    | '/oficina/ordens'
    | '/vendas/estoque'
    | '/vendas/loja-virtual'
    | '/vendas/nova'
    | '/vendas/produtos'
    | '/vendas/$id'
    | '/vendas'
  id:
    | '__root__'
    | '/_app'
    | '/login'
    | '/_app/bikes'
    | '/_app/clientes'
    | '/_app/compras'
    | '/_app/configuracoes'
    | '/_app/contas-a-pagar'
    | '/_app/despesas'
    | '/_app/fechamento'
    | '/_app/fornecedores'
    | '/_app/marcas'
    | '/_app/marketing'
    | '/_app/oficina'
    | '/_app/parametros-financeiros'
    | '/_app/parametros-nfe'
    | '/_app/pendencias'
    | '/_app/precos'
    | '/_app/relatorios'
    | '/_app/tipos-atividade'
    | '/_app/vendas'
    | '/_app/'
    | '/_app/b/$codigo'
    | '/_app/bikes_/$id'
    | '/_app/clientes_/$id'
    | '/_app/clientes_/nova'
    | '/_app/fornecedores_/$id'
    | '/_app/oficina_/nova'
    | '/_app/oficina_/ordens'
    | '/_app/vendas/estoque'
    | '/_app/vendas/loja-virtual'
    | '/_app/vendas/nova'
    | '/_app/vendas/produtos'
    | '/_app/vendas_/$id'
    | '/_app/vendas/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/vendas': {
      id: '/_app/vendas'
      path: '/vendas'
      fullPath: '/vendas'
      preLoaderRoute: typeof AppVendasRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/tipos-atividade': {
      id: '/_app/tipos-atividade'
      path: '/tipos-atividade'
      fullPath: '/tipos-atividade'
      preLoaderRoute: typeof AppTiposAtividadeRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/relatorios': {
      id: '/_app/relatorios'
      path: '/relatorios'
      fullPath: '/relatorios'
      preLoaderRoute: typeof AppRelatoriosRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/precos': {
      id: '/_app/precos'
      path: '/precos'
      fullPath: '/precos'
      preLoaderRoute: typeof AppPrecosRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/pendencias': {
      id: '/_app/pendencias'
      path: '/pendencias'
      fullPath: '/pendencias'
      preLoaderRoute: typeof AppPendenciasRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/parametros-nfe': {
      id: '/_app/parametros-nfe'
      path: '/parametros-nfe'
      fullPath: '/parametros-nfe'
      preLoaderRoute: typeof AppParametrosNfeRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/parametros-financeiros': {
      id: '/_app/parametros-financeiros'
      path: '/parametros-financeiros'
      fullPath: '/parametros-financeiros'
      preLoaderRoute: typeof AppParametrosFinanceirosRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/oficina': {
      id: '/_app/oficina'
      path: '/oficina'
      fullPath: '/oficina'
      preLoaderRoute: typeof AppOficinaRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/marketing': {
      id: '/_app/marketing'
      path: '/marketing'
      fullPath: '/marketing'
      preLoaderRoute: typeof AppMarketingRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/marcas': {
      id: '/_app/marcas'
      path: '/marcas'
      fullPath: '/marcas'
      preLoaderRoute: typeof AppMarcasRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/fornecedores': {
      id: '/_app/fornecedores'
      path: '/fornecedores'
      fullPath: '/fornecedores'
      preLoaderRoute: typeof AppFornecedoresRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/fechamento': {
      id: '/_app/fechamento'
      path: '/fechamento'
      fullPath: '/fechamento'
      preLoaderRoute: typeof AppFechamentoRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/despesas': {
      id: '/_app/despesas'
      path: '/despesas'
      fullPath: '/despesas'
      preLoaderRoute: typeof AppDespesasRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/contas-a-pagar': {
      id: '/_app/contas-a-pagar'
      path: '/contas-a-pagar'
      fullPath: '/contas-a-pagar'
      preLoaderRoute: typeof AppContasAPagarRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/configuracoes': {
      id: '/_app/configuracoes'
      path: '/configuracoes'
      fullPath: '/configuracoes'
      preLoaderRoute: typeof AppConfiguracoesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/compras': {
      id: '/_app/compras'
      path: '/compras'
      fullPath: '/compras'
      preLoaderRoute: typeof AppComprasRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/clientes': {
      id: '/_app/clientes'
      path: '/clientes'
      fullPath: '/clientes'
      preLoaderRoute: typeof AppClientesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/bikes': {
      id: '/_app/bikes'
      path: '/bikes'
      fullPath: '/bikes'
      preLoaderRoute: typeof AppBikesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/vendas/': {
      id: '/_app/vendas/'
      path: '/'
      fullPath: '/vendas/'
      preLoaderRoute: typeof AppVendasIndexRouteImport
      parentRoute: typeof AppVendasRoute
    }
    '/_app/vendas_/$id': {
      id: '/_app/vendas_/$id'
      path: '/vendas/$id'
      fullPath: '/vendas/$id'
      preLoaderRoute: typeof AppVendasIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/vendas/produtos': {
      id: '/_app/vendas/produtos'
      path: '/produtos'
      fullPath: '/vendas/produtos'
      preLoaderRoute: typeof AppVendasProdutosRouteImport
      parentRoute: typeof AppVendasRoute
    }
    '/_app/vendas/nova': {
      id: '/_app/vendas/nova'
      path: '/nova'
      fullPath: '/vendas/nova'
      preLoaderRoute: typeof AppVendasNovaRouteImport
      parentRoute: typeof AppVendasRoute
    }
    '/_app/vendas/loja-virtual': {
      id: '/_app/vendas/loja-virtual'
      path: '/loja-virtual'
      fullPath: '/vendas/loja-virtual'
      preLoaderRoute: typeof AppVendasLojaVirtualRouteImport
      parentRoute: typeof AppVendasRoute
    }
    '/_app/vendas/estoque': {
      id: '/_app/vendas/estoque'
      path: '/estoque'
      fullPath: '/vendas/estoque'
      preLoaderRoute: typeof AppVendasEstoqueRouteImport
      parentRoute: typeof AppVendasRoute
    }
    '/_app/oficina_/ordens': {
      id: '/_app/oficina_/ordens'
      path: '/oficina/ordens'
      fullPath: '/oficina/ordens'
      preLoaderRoute: typeof AppOficinaOrdensRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/oficina_/nova': {
      id: '/_app/oficina_/nova'
      path: '/oficina/nova'
      fullPath: '/oficina/nova'
      preLoaderRoute: typeof AppOficinaNovaRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/fornecedores_/$id': {
      id: '/_app/fornecedores_/$id'
      path: '/fornecedores/$id'
      fullPath: '/fornecedores/$id'
      preLoaderRoute: typeof AppFornecedoresIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/clientes_/nova': {
      id: '/_app/clientes_/nova'
      path: '/clientes/nova'
      fullPath: '/clientes/nova'
      preLoaderRoute: typeof AppClientesNovaRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/clientes_/$id': {
      id: '/_app/clientes_/$id'
      path: '/clientes/$id'
      fullPath: '/clientes/$id'
      preLoaderRoute: typeof AppClientesIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/bikes_/$id': {
      id: '/_app/bikes_/$id'
      path: '/bikes/$id'
      fullPath: '/bikes/$id'
      preLoaderRoute: typeof AppBikesIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/b/$codigo': {
      id: '/_app/b/$codigo'
      path: '/b/$codigo'
      fullPath: '/b/$codigo'
      preLoaderRoute: typeof AppBCodigoRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppVendasRouteChildren {
  AppVendasEstoqueRoute: typeof AppVendasEstoqueRoute
  AppVendasLojaVirtualRoute: typeof AppVendasLojaVirtualRoute
  AppVendasNovaRoute: typeof AppVendasNovaRoute
  AppVendasProdutosRoute: typeof AppVendasProdutosRoute
  AppVendasIndexRoute: typeof AppVendasIndexRoute
}

const AppVendasRouteChildren: AppVendasRouteChildren = {
  AppVendasEstoqueRoute: AppVendasEstoqueRoute,
  AppVendasLojaVirtualRoute: AppVendasLojaVirtualRoute,
  AppVendasNovaRoute: AppVendasNovaRoute,
  AppVendasProdutosRoute: AppVendasProdutosRoute,
  AppVendasIndexRoute: AppVendasIndexRoute,
}

const AppVendasRouteWithChildren = AppVendasRoute._addFileChildren(
  AppVendasRouteChildren,
)

interface AppRouteChildren {
  AppBikesRoute: typeof AppBikesRoute
  AppClientesRoute: typeof AppClientesRoute
  AppComprasRoute: typeof AppComprasRoute
  AppConfiguracoesRoute: typeof AppConfiguracoesRoute
  AppContasAPagarRoute: typeof AppContasAPagarRoute
  AppDespesasRoute: typeof AppDespesasRoute
  AppFechamentoRoute: typeof AppFechamentoRoute
  AppFornecedoresRoute: typeof AppFornecedoresRoute
  AppMarcasRoute: typeof AppMarcasRoute
  AppMarketingRoute: typeof AppMarketingRoute
  AppOficinaRoute: typeof AppOficinaRoute
  AppParametrosFinanceirosRoute: typeof AppParametrosFinanceirosRoute
  AppParametrosNfeRoute: typeof AppParametrosNfeRoute
  AppPendenciasRoute: typeof AppPendenciasRoute
  AppPrecosRoute: typeof AppPrecosRoute
  AppRelatoriosRoute: typeof AppRelatoriosRoute
  AppTiposAtividadeRoute: typeof AppTiposAtividadeRoute
  AppVendasRoute: typeof AppVendasRouteWithChildren
  AppIndexRoute: typeof AppIndexRoute
  AppBCodigoRoute: typeof AppBCodigoRoute
  AppBikesIdRoute: typeof AppBikesIdRoute
  AppClientesIdRoute: typeof AppClientesIdRoute
  AppClientesNovaRoute: typeof AppClientesNovaRoute
  AppFornecedoresIdRoute: typeof AppFornecedoresIdRoute
  AppOficinaNovaRoute: typeof AppOficinaNovaRoute
  AppOficinaOrdensRoute: typeof AppOficinaOrdensRoute
  AppVendasIdRoute: typeof AppVendasIdRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppBikesRoute: AppBikesRoute,
  AppClientesRoute: AppClientesRoute,
  AppComprasRoute: AppComprasRoute,
  AppConfiguracoesRoute: AppConfiguracoesRoute,
  AppContasAPagarRoute: AppContasAPagarRoute,
  AppDespesasRoute: AppDespesasRoute,
  AppFechamentoRoute: AppFechamentoRoute,
  AppFornecedoresRoute: AppFornecedoresRoute,
  AppMarcasRoute: AppMarcasRoute,
  AppMarketingRoute: AppMarketingRoute,
  AppOficinaRoute: AppOficinaRoute,
  AppParametrosFinanceirosRoute: AppParametrosFinanceirosRoute,
  AppParametrosNfeRoute: AppParametrosNfeRoute,
  AppPendenciasRoute: AppPendenciasRoute,
  AppPrecosRoute: AppPrecosRoute,
  AppRelatoriosRoute: AppRelatoriosRoute,
  AppTiposAtividadeRoute: AppTiposAtividadeRoute,
  AppVendasRoute: AppVendasRouteWithChildren,
  AppIndexRoute: AppIndexRoute,
  AppBCodigoRoute: AppBCodigoRoute,
  AppBikesIdRoute: AppBikesIdRoute,
  AppClientesIdRoute: AppClientesIdRoute,
  AppClientesNovaRoute: AppClientesNovaRoute,
  AppFornecedoresIdRoute: AppFornecedoresIdRoute,
  AppOficinaNovaRoute: AppOficinaNovaRoute,
  AppOficinaOrdensRoute: AppOficinaOrdensRoute,
  AppVendasIdRoute: AppVendasIdRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
